<?php

class CellCarriers {
    public static $carriers = Array (
        "AT&T" => "txt.att.net",
        "T-Mobile" => "tmomail.net",
        "Sprint" => "messaging.sprint.com",
        "Verizon" => "vtext.com",
        "3 River Wireless" => "sms.3rivers.net",
        "ACS Wireless" => "paging.acswireless.com",
        "Alltel" => "message.alltel.com",
        "Bell Canada" => "txt.bellmobility.ca",
        "Blue Sky Frog" => 'blueskyfrog.com',
        "Bluegrass Cellular" => "sms.bluecell.com",
        "Boost Mobile" => "myboostmobile.com",
        // skipped some tbh
        "Cellular One" => "mobile.celloneusa.com",
        "Cellular South" => "10digitphonenumber@csouth1.com",
        // skipped some more
        "CenturyTel" => "messaging.centurytel.net",
        "Clearnet" => "msg.clearnet.com",
        "Comcast" => "comcastpcs.textmsg.com",
        "Corr Wireless Communication" => "corrwireless.net",
        "Dobson" => "mobile.dobson.net",
        "Edge Wireless" => "sms.edgewireless.com",
        "Fido" => "fido.ca",
        "Golden Telecom" => "sms.goldentelecom.com",
        "Helio" => "messaging.sprintpcs.com",
        "Houston Cellular" => "text.houstoncellular.net",
        "Idea Cellular" => "ideacellular.net",
        "Illinois Valley Cellular" => "ivctext.com",
        "Inland Cellular Telephone" => "inlandlink.com",
        "MCI" => "pagemci.com",
        "Metrocall" => "page.metrocall.com",
        "Metrocall 2-way" => "my2way.com",
        "Metro PCS" => "mymetropcs.com",
        "Microcell" => "fido.ca",
        "Midwest Wireless" => "clearlydigital.com",
        "Mobilcomm" => "mobilecomm.net",
        "MTS" => "text.mtsmobility.com",
        "Nextel" => "messaging.nextel.com",
        "OnlineBeep" => "onlinebeep.net",
        "PCS One" => "pcsone.net",
        "President's Choice" => "txt.bell.ca",
        "Public Service Cellular" => "sms.pscel.com",
        "Qwest" => "qwestmp.com",
        "Rogers" => "pcs.rogers.com",
        "Solo Mobile" => "txt.bell.ca",
        "Southwestern Bell" => "email.swbw.com",
        "Suncom" => "tms.suncom.com",
        "Surewest" => "mobile.surewest.com",
        "Telus" => "msg.telus.com",
        "Tracfone" => "txt.att.net",
        "Triton" => "tms.suncom.com",
        "Unicel" => "utext.com",
        "US Cellular" => "email.uscc.net",
        "Virgin Mobile" => "vmobl.com",
        "Virgin Mobile Canada" => "vmobile.ca",
        "West Central Wireless" => "sms.wcc.net",
        "Western Wireless" => "cellularonewest.com"
        
    );
};

?>