DROP DATABASE IF EXISTS motely;
CREATE DATABASE motely;
USE motley;

-- Create the tables

CREATE TABLE employee (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(256)
);


CREATE TABLE customer (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  phone VARCHAR(64) NOT NULL,
  email VARCHAR(64) NOT NULL,
  carrier VARCHAR(64) NOT NULL
);

CREATE TABLE order (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  customer_id INT UNSIGNED NOT NULL,
  price FLOAT NOT NULL,
  ordertime TIMESTAMP CURRENT_TIMESTAMP,
  FOREIGN KEY (customer_id) REFERENCES customer(id),
);

CREATE TABLE CustomDrink (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  order_id INT UNSIGNED NOT NULL,
  type_id INT UNSIGNED NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  price FLOAT,
  FOREIGN KEY (order_id) REFERENCES order(id),
  FOREIGN KEY (type_id) REFERENCES DrinkType(id)
);

CREATE TABLE DrinkType (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64),
  price FLOAT NOT NULL
);
